### ISSUE TITLE
Various fixes

### ISSUE THREAD

**Issue by turtlebyturtle** [Urth-Forum-Roleplay/urthmaps#104]
Some of these problems seem older than others, mostly nation labels overlapping with cities

Spotted so far:
- Wed Shams
- Transnalpia

**Comment by turtlebyturtle** [comment]
E-W Cerdani as well

**Comment by turtlebyturtle** [comment]
Ariundun (Lower Suvania, near Vistaraland) is on nat layer instead of cities layer

**Comment by turtlebyturtle** [comment]
Border in white area west of west cerdani

**Comment by tretrid** [comment]
Fixed all issues except the Cerdani labels - could not find anything wrong with the nation labels there.
