### ISSUE TITLE
Aranthia

### ISSUE THREAD

**Issue by tretrid** [Urth-Forum-Roleplay/urthmaps#169]
**Claim link:** https://forum.theeastpacific.com/t/aranthia-claim/18107/3
**Vote result:** Approved 5/4/0
**Additional files/links:**
**Notes:**

**Comment by turtlebyturtle** [comment]
Cities: https://forum.theeastpacific.com/t/map-changes/16229/75

**Comment by turtlebyturtle** [comment]
Awaiting new cities

**Comment by turtlebyturtle** [comment]
New cities: https://forum.theeastpacific.com/t/map-changes/16229/75?u=turtle
